### ISSUE TITLE
Text to speech localization

### ISSUE THREAD

**Issue by Joostvt** [JuliusSweetland/OptiKey#106]
Hello,

How could we translate the text to speech functionality?

Your sincerely,

Joost van Tricht

**Comment by delta003** [comment]
Assuming there is a internet connection, we can just use Google TTS API
(e.g. http://translate.google.com/translate_tts?tl=en&q=Integrate%20text%20to%20speech)
It should be fast enough and I think it covers all languages as Google Translate

**Comment by JuliusSweetland** [comment]
Thank you - do you have a link to read about the TTS API for C# (or whatever I can consume from C#)? That link just takes me to a sample audio clip.

**Comment by delta003** [comment]
No, the link is the example of HTTP request. You just make HTTP to translate.google.com/translate_tts setting tl=language (two letters shortcut for language) and query=what_do_you_want_to_say (make sure you escape this string). HTTP response have Content-Type:audio/mpeg so from response you can get audio file. Then you just pass that file to system to play it (I'm don't really know C# but this should be easy). Here are some useful links:
http://stackoverflow.com/questions/184683/play-audio-from-a-stream-using-c-sharp
http://stackoverflow.com/questions/7757881/c-sharp-download-text-to-speech-from-google-translate-comes-with-problems
http://stackoverflow.com/questions/9243560/how-can-i-use-google-text-to-speech-api-in-windows-form
I don't have access to Windows now, so I can't implement this, but if you want I can write you a class that implements IAudioService and use this approach. But you'll have to check it and probably debug it. Just ping me here if you need that. Also, I'll have access to windows in ~month so if this issue is still open I'll develop a feature.

**Comment by JuliusSweetland** [comment]
Awesome, thanks. Hold off until you have a Windows machine again and then
we can pick this up when I have a bit more time to spend on it. I would
also like to split out the IAudioService as it's currently in breach of the
single responsibility principle. There should really be an interface and
class for playing sounds and an interface and multiple classes for speech.
Then I can just swap out one speech service for another, and even nest them
so we can fall back to Microsoft TTS if there is no active internet
connection, for example.

**Comment by delta003** [comment]
Yes, that would be the best option. Just keep this issue updated so I can pick it up eventually.

**Comment by JuliusSweetland** [comment]
I'll leave it open. I'll only add to it if I have any interesting thoughts
on topic, otherwise it'll be here when you come back.

**Comment by JuliusSweetland** [comment]
Closing this issue as this is covered by #108. I will re-post the info from here and link across.
