### ISSUE TITLE
Auditory trigger

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#26]
Sound activated trigger.

Throat mounted microphone.

Would need a calibration step to get levels.

**Comment by feugy** [comment]
Hi Julius.

I've started few months ago a [kind of similar project](https://github.com/feugy/alfred) for my father-in-law, affected by ALS.
A colleague of mine found your amazing work through Reddit, and it's what I've dreamed to create (with a loooot of extra features)

On my side, I tried to use a mix of gaze and voice input to allow a quicker usage (especially when it comes to browse web page with multiple click and scroll actions)
I've had very hard times trying to have both keyword recognition and natural language recognition, ending to an abandon due to lack of time.

I was wondering if you will accept a small contribution on adding spoken (perhaps parametrized) key word trigger, and a french localization also.

**Comment by JuliusSweetland** [comment]
I'm certainly interested in looking into the possibility of sharing features to produce a richer application. Can you drop me an email and we can discuss this further; optikeyfeedback@gmail.com

**Comment by JuliusSweetland** [comment]
Adding to BACKLOG

**Comment by alexandre-mbm** [comment]
I am thinking in voice commands given by carers. Auxiliary commands.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm Have a look at the voice commands pull request created by feugy. It works well, but needs testing. I had some issues with it recognising incorrect words so I never got around to merging the work, but the foundation is good - you might want to take a look and work on this to finish it?

**Comment by alexandre-mbm** [comment]
> Have a look at the voice commands pull request created by feugy.

#173 and #276

**Comment by JuliusSweetland** [comment]
It's #173 - the other one is rubbish.
