### ISSUE TITLE
Gaze gestures

### ISSUE THREAD

**Issue by arya-s** [JuliusSweetland/OptiKey#87]
Instead of dwelling to complete a word, consider adding gaze gestures as a second option.

To begin with, it would be very easy to detect a submit based on if the user's gaze leaves the screen over one of the 4 edges of a screen/optikey boundaries. This would allow much faster interaction.

**Comment by DanielHutt** [comment]
The problem with this is that if the user gets distracted or looks at something on the non-keyboard portion of the screen, the gesture is going to get messed up.  Just voicing a concern, not saying it can't be done!

**Comment by willianfatec** [comment]
Sorry, I don't understand completely that discussion. Anyway here you have some options that I consider possible to use. 
Consider to use a floating button or a pie menu that just appear when the user look to the word in order to choose the right word on the screen. 
Some studies has used one-eye blinking to confirm or execute commands. 

In case that I have misunderstood the problem, please clarify me.

**Comment by arya-s** [comment]
@DanielHutt in that case it's probably better to use the edge screens.

Also sure messing up is a concern, but so can be dwell time based entering. I still think you'd gain typing speed. We could compensate by giving a last word delete option.

@willianfatec the problem with floating button is that it will automatically capture your attention and you can't execute just because the user gazed there. He will look there almost certainly. So you don't really gain anything by doing that as you would still need dwell time on that button.

**Comment by JuliusSweetland** [comment]
Adding to general list of potential ideas (https://github.com/JuliusSweetland/OptiKey/issues/57)

**Comment by alexandre-mbm** [comment]
+1 for gaze gestures + blink switches, configurable and combinable in _n_ ways. It is not need begin this to be to configured by user; could be by carer only.
